# Configuration file for FluxPulse algorithm

# Define dataset directories
data_dirs:
  ancillary_dir: "data/"      
  input_dir: "data/full_FLUXNET_formatted_data/"
# Output directory
output_dir: "results_final/"
output_dir_during_pulse: "results_step1/"
