# Configuration file for FluxPulse algorithm

# Define dataset directories
data_dirs:
  ancillary_dir: "data/"      
  input_dir: "data/full_FLUXNET_formatted_data/"
# Output directory
output_dir_bias_correction: "results/bias_correction/bias_correction_during_all_time/"
output_dir_bias_correction_during_pulse: "results/bias_correction/bias_correction_during_pulse/"
output_dir_ML_detection: "results/ML_detection/"
